"""Bilingual presentation data and rule-drift assertions."""

UI = {
    "ua": {
        "title": "Темна Рада",
        "subtitle": "Три раунди переговорів. Кімната, повна брехні. Усе вирішать фінальні вибори.",
        "player": "Гравець",
        "syndicate": "Синдикат",
        "gm": "Ведучий",
        "quick": "Швидка пам'ятка",
        "diagrams": "Схеми",
        "flow": "Хід гри",
        "choose_count": "Гравців",
        "setup_summary": "Склад і пороги",
        "player_count": "Кількість гравців",
        "magnate_count": "Магнатів",
        "contents": "Зміст",
        "theme_toggle": "Світла / темна тема",
        "five_things": "П'ять речей, які треба пам'ятати",
        "glossary": "Короткий словник",
        "print": "Друк",
        "round": "Раунд",
        "prep": "Підготовка",
        "final": "Фінал",
        "hit": "Замовлення",
        "private": "Приватна фаза",
        "council": "Рада",
        "leaders": "Топ-3",
        "auction": "Аукціон",
        "payout": "+2 кожному живому гравцю",
        "interrogation": "Три наслідки Допиту",
        "vote_fails": "Голосування не пройшло",
        "innocent_dies": "Страчено Невинного",
        "assassin_dies": "Страчено Вбивцю",
        "evidence": "П'ять Доказів",
        "false": "2 хибні",
        "true": "3 правдиві",
        "auction_truth": "Аукціон: гарантована правда",
        "final_flow": "Як проходить Фінал",
        "nominate": "3 висування",
        "reveal": "Розкриття",
        "buy": "Купівля голосів",
        "ballot": "Таємні вибори",
        "victory": "Перевірка перемоги",
        "thresholds": "Пороги для цієї кількості гравців",
        "magnates_need": "Поріг Магнатів",
        "syndicate_needs": "Вбивця + Криївка",
        "factions": "Аристократи / Реформісти",
        "magnates": "Магнати",
        "start_here": "Почніть тут",
        "current_path": "Що читати",
        "skip": "До правил",
    },
    "en": {
        "title": "The Dark Council",
        "subtitle": "Three rounds of negotiation. One room full of lies. A final election decides everything.",
        "player": "Player",
        "syndicate": "Syndicate",
        "gm": "GM",
        "quick": "Quick reference",
        "diagrams": "Diagrams",
        "flow": "Game flow",
        "choose_count": "Players",
        "setup_summary": "Setup and thresholds",
        "player_count": "Player count",
        "magnate_count": "Magnates",
        "contents": "Contents",
        "theme_toggle": "Light / dark theme",
        "five_things": "Track only five things",
        "glossary": "Short glossary",
        "print": "Print",
        "round": "Round",
        "prep": "Preparation",
        "final": "Final",
        "hit": "Hit",
        "private": "Private phase",
        "council": "Council",
        "leaders": "Top 3",
        "auction": "Auction",
        "payout": "+2 to every living player",
        "interrogation": "Three Interrogation outcomes",
        "vote_fails": "Vote fails",
        "innocent_dies": "Innocent executed",
        "assassin_dies": "Assassin executed",
        "evidence": "Five Evidence statements",
        "false": "2 false",
        "true": "3 true",
        "auction_truth": "Auction: guaranteed truth",
        "final_flow": "How the Final works",
        "nominate": "3 nominations",
        "reveal": "Reveal",
        "buy": "Buy votes",
        "ballot": "Secret election",
        "victory": "Victory check",
        "thresholds": "Thresholds for this player count",
        "magnates_need": "Magnate threshold",
        "syndicate_needs": "Assassin + Stash",
        "factions": "Aristocrats / Reformers",
        "magnates": "Magnates",
        "start_here": "Start here",
        "current_path": "Reading mode",
        "skip": "Skip to rules",
    },
}

FIVE_THINGS = {
    "ua": [
        ("Вплив", "Ваші фішки та борг, записаний Ведучим."),
        ("Фракція", "Кого Ви хочете бачити при владі."),
        ("Цілі", "Мотив +5 та Амбіція +10."),
        ("Секрет", "Його можна правильно Викрити лише раз."),
        ("Інформація", "Докази, Компромат, угоди та підозри."),
    ],
    "en": [
        ("Influence", "Your chips and any debt recorded by the GM."),
        ("Faction", "Who you want to put in power."),
        ("Goals", "A +5 Motive and +10 Ambition."),
        ("Secret", "It can be exposed correctly only once."),
        ("Information", "Evidence, Secret Intelligence, deals and suspicions."),
    ],
}

GLOSSARY = {
    "ua": [
        {"id": "influence", "term": "Вплив", "pattern": r"Вплив(?:у|ом|ові|и|ів|ам|ами|ах)?", "definition": "Фізична валюта гри: одна фішка дорівнює одному Впливу."},
        {"id": "faction", "term": "Фракція", "pattern": r"Фракці(?:я|ї|ю|єю|ям|ями|ях)", "definition": "Політичний табір гравця: Аристократи, Реформісти або Магнати."},
        {"id": "syndicate", "term": "Синдикат", "pattern": r"Синдикат(?:у|ом|і)?", "definition": "Таємна команда з двох гравців: Вбивці та Спільника."},
        {"id": "assassin", "term": "Вбивця", "pattern": r"Вбивц(?:я|і|ю|ею|ем|ів|ям|ями|ях)", "definition": "Член Синдикату, який обирає одну ціль для вбивства в кожному раунді."},
        {"id": "accomplice", "term": "Спільник", "pattern": r"Спільник(?:а|у|ом|ові|и|ів|ам|ами|ах)?", "definition": "Другий член Синдикату; після Страти Вбивці перебирає його роль."},
        {"id": "stash", "term": "Криївка", "pattern": r"(?:Криївк(?:а|и|у|ою|ам|ами|ах)|Криївці)", "definition": "Таємний запас Впливу Синдикату, який веде Ведучий."},
        {"id": "hit", "term": "Замовлення", "pattern": r"Замовленн(?:я|ю|ям|ями|ях)", "definition": "На початку кожного раунду Ведучий публічно оголошує Замовлення на вбивство для Синдикату. Воно називає прикмету жертви, яку Синдикат має вбити, але ніколи не вказує на конкретного гравця."},
        {"id": "bankruptcy", "term": "Банкрутство", "pattern": r"Банкрутств(?:о|а|у|ом|і)", "definition": "Від'ємний баланс до Фіналу є боргом. На початку Фіналу Ведучий оголошує Банкрутами всіх, хто досі має борг. Вони не можуть бути Кандидатами й особисто не отримують Перемогу Фракції."},
        {"id": "intelligence", "term": "Компромат", "pattern": r"Компромат(?:у|ом|і)?", "definition": "Правдивий Секрет одного конкретного гравця."},
        {"id": "evidence", "term": "Доказ", "pattern": r"Доказ(?:у|ом|і|и|ів|ам|ами|ах)?", "definition": "Твердження про Синдикат. У грі їх п'ять, і рівно два з них хибні."},
        {"id": "interrogation", "term": "Допит", "pattern": r"Допит(?:у|ом|і|и|ів|ам|ами|ах)?", "definition": "Платне публічне звинувачення гравця в тому, що він є чинним Вбивцею. Голосують Привиди та живі гравці, які мають щонайменше 1 Впливу."},
        {"id": "expose", "term": "Викриття", "pattern": r"Викритт(?:я|ю|і|ям|ями|ях)", "definition": "Публічна спроба правильно назвати Секрет іншого гравця. Щоб зробити спробу, потрібно мати щонайменше 2 Впливу."},
        {"id": "execution", "term": "Страта", "pattern": r"Страт(?:а|и|у|ою|і)", "definition": "Смерть гравця внаслідок успішного голосування на Допиті."},
        {"id": "ghost", "term": "Привид", "pattern": r"Привид(?:а|у|ом|і|и|ів|ам|ами|ах)?", "definition": "Мертвий гравець, який і далі бере участь у голосуваннях та спільному питанні Привидів."},
        {"id": "auction", "term": "Аукціон", "pattern": r"Аукціон(?:у|ом|і|и|ів|ам|ами|ах)?", "definition": "Торги в Раунді 2 за один гарантовано правдивий Доказ."},
        {"id": "motive", "term": "Мотив", "pattern": r"Мотив(?:у|ом|і|и|ів|ам|ами|ах)?", "definition": "Мала особиста Ціль, за яку гравець отримує +5 Впливу."},
        {"id": "ambition", "term": "Амбіція", "pattern": r"Амбіці(?:я|ї|ю|єю|ям|ями|ях)", "definition": "Велика особиста Ціль, за яку гравець отримує +10 Впливу."},
        {"id": "reveal", "term": "Розкриття", "pattern": r"Розкритт(?:я|ю|і|ям|ями|ях)", "definition": "Фінальне голосування, яке публічно відкриває Фракцію обраного гравця."},
    ],
    "en": [
        {"id": "influence", "term": "Influence", "pattern": r"Influence", "definition": "The game's physical currency: one chip equals one Influence."},
        {"id": "faction", "term": "Faction", "pattern": r"Factions?", "definition": "A player's political camp: Aristocrat, Reformer or Magnate."},
        {"id": "syndicate", "term": "Syndicate", "pattern": r"Syndicate", "definition": "The hidden two-player team: the Assassin and Accomplice."},
        {"id": "assassin", "term": "Assassin", "pattern": r"Assassins?", "definition": "The Syndicate member who chooses one assassination target each round."},
        {"id": "accomplice", "term": "Accomplice", "pattern": r"Accomplices?", "definition": "The second Syndicate member, who takes over if the Assassin is Executed."},
        {"id": "stash", "term": "Stash", "pattern": r"Stash", "definition": "The Syndicate's hidden Influence reserve, tracked by the GM."},
        {"id": "hit", "term": "Hit", "pattern": r"Hits?", "definition": "At the start of each round, the GM announces a Hit: an assassination order for the Syndicate. It names a trait of the required victim and never a specific player."},
        {"id": "bankruptcy", "term": "Bankruptcy", "pattern": r"Bankrupt(?:cy)?", "definition": "A negative balance before the Final is debt. At the start of the Final, the GM declares every player still in debt Bankrupt. They cannot be Candidates and do not personally receive a Faction Victory."},
        {"id": "intelligence", "term": "Secret Intelligence", "pattern": r"Secret Intelligence", "definition": "The true Secret of one named player."},
        {"id": "evidence", "term": "Evidence", "pattern": r"Evidence", "definition": "A statement about the Syndicate. There are five, exactly two of them false."},
        {"id": "interrogation", "term": "Interrogation", "pattern": r"Interrogations?", "definition": "A paid public accusation that a player is the current Assassin. Ghosts and living players with at least 1 Influence vote."},
        {"id": "expose", "term": "Expose", "pattern": r"Expose(?:d|s)?", "definition": "A public attempt to name another player's Secret correctly. Attempting it requires at least 2 Influence."},
        {"id": "execution", "term": "Execution", "pattern": r"Execut(?:e|ed|ion|ions)", "definition": "A player's death following a successful Interrogation vote."},
        {"id": "ghost", "term": "Ghost", "pattern": r"Ghosts?", "definition": "A dead player who still votes and helps ask one shared private question."},
        {"id": "auction", "term": "Auction", "pattern": r"Auction", "definition": "Round 2 bidding for one guaranteed true Evidence statement."},
        {"id": "motive", "term": "Motive", "pattern": r"Motives?", "definition": "A small personal Goal worth +5 Influence."},
        {"id": "ambition", "term": "Ambition", "pattern": r"Ambitions?", "definition": "A large personal Goal worth +10 Influence."},
        {"id": "reveal", "term": "Reveal", "pattern": r"Reveal", "definition": "The Final vote that publicly reveals one chosen player's Faction."},
    ],
}

FACTIONS = {
    "ua": [
        ("aristocrat", "Аристократи", "Перемагає Кандидат-Аристократ."),
        ("reformer", "Реформісти", "Перемагає Кандидат-Реформіст."),
        ("magnate", "Магнати", "Живі Магнати зберігають достатньо сумарного Впливу."),
        ("syndicate", "Синдикат", "Чинний Вбивця живий і разом із Криївкою досягає порога."),
    ],
    "en": [
        ("aristocrat", "Aristocrats", "An Aristocrat Candidate wins the election."),
        ("reformer", "Reformers", "A Reformer Candidate wins the election."),
        ("magnate", "Magnates", "The living Magnates retain enough combined Influence."),
        ("syndicate", "Syndicate", "The current Assassin survives and reaches the threshold with the Stash."),
    ],
}

# Each item is (section number, regex). The generator refuses to build if it drifts.
RULE_ASSERTIONS = {
    "ua": [
        (1, r"\+2 Впливу"),
        (1, r"30 хвилин"),
        (1, r"45 хвилин"),
        (1, r"60 хвилин"),
        (3, r"залишається 5 хвилин і 1 хвилина"),
        (2, r"4 стартові фішки"),
        (6, r"перший Допит.*4 Впливу"),
        (6, r"на\s+1 Вплив більше"),
        (6, r"отримує \+3 Впливу"),
        (6, r"втрачає \*\*1 Вплив\*\*"),
        (6, r"отримує \*\*\+5 Впливу\*\*"),
        (6, r"ціль втрачає 4 Впливу"),
        (6, r"Ви отримуєте 1 Вплив"),
        (6, r"Ви втрачаєте 2 Впливу"),
        (7, r"рівно \*\*п'ять\*\*"),
        (7, r"Рівно\s+\*\*два з п'яти є хибними\*\*"),
        (9, r"по 1 Впливу"),
        (9, r"\*\*3 Впливу за голос\*\*"),
        (11, r"до 2 Впливу за раунд"),
        (11, r"додайте 3 Впливу"),
        (4, r"найбільший негайний штраф"),
        (6, r"щонайменше 2 Впливу"),
        (6, r"живі гравці.*щонайменше 1 Впливу"),
        (9, r"фіксує Банкрутство"),
        (5, r"Заявляйте виконану Ціль приватно"),
        (5, r"\*\*3 Впливу чистого прибутку\*\*"),
        (5, r"Окремий журнал не потрібен"),
        (11, r"Вбивця зобов'язаний подати одну чинну ціль"),
        (12, r"Аристократів і Реформістів завжди однакова"),
    ],
    "en": [
        (1, r"\+2 Influence"),
        (1, r"30 minutes"),
        (1, r"45 minutes"),
        (1, r"60 minutes"),
        (3, r"5 minutes and 1 minute remain"),
        (2, r"4 starting Influence"),
        (6, r"first Interrogation.*4 Influence"),
        (6, r"costs 1 more"),
        (6, r"gains \+3 Influence"),
        (6, r"loses \*\*1 Influence\*\*"),
        (6, r"gains \*\*\+5 Influence\*\*"),
        (6, r"target loses 4 Influence"),
        (6, r"You gain 1 Influence"),
        (6, r"You lose 2 Influence"),
        (7, r"exactly \*\*five\*\*"),
        (7, r"Exactly\s+\*\*two of the five are false\*\*"),
        (9, r"for 1 Influence each"),
        (9, r"\*\*3 Influence per vote\*\*"),
        (11, r"up to 2 per round"),
        (11, r"add 3 Influence"),
        (4, r"largest immediate penalty"),
        (6, r"at least 2 Influence"),
        (6, r"living player.*at least 1 Influence"),
        (9, r"fixes Bankruptcy"),
        (5, r"Claim a completed Goal privately"),
        (5, r"\*\*3 Influence in net profit\*\*"),
        (5, r"No separate ledger is required"),
        (11, r"The Assassin must submit one valid target"),
        (12, r"Aristocrats and Reformers always have equal numbers"),
    ],
}

SYNDICATE_ONLY_TERMS = {
    "ua": ("Відмивання", "Підвищення"),
    "en": ("Launder", "Promotion"),
}
